name: Run Tests

on:
  pull_request:
  push:
    branches: [ master, main ]
    tags: [ "*" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-cache
      - name: Compile and Check Formatting
        run: sbt test
